package com.vincenzoracca.localstack.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@DynamoDBTable(tableName = "Cars")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Car {

    private String id;

    private String code;

    private String name;

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute(attributeName = "Code")
    public String getCode() {
        return code;
    }

    @DynamoDBAttribute(attributeName = "Name")
    public String getName() {
        return name;
    }
}
